# Generated by Django 2.2.5 on 2019-09-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=20, unique=True)),
                ('contract_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contract', models.CharField(max_length=100, unique=True)),
                ('doc_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_distance', models.PositiveIntegerField()),
                ('besar_upah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('corporate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('corporate_address', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_usaha', models.CharField(blank=True, max_length=50, null=True)),
                ('jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('cara_pembayaran', models.CharField(blank=True, max_length=50, null=True)),
                ('tempat_aggrement', models.CharField(blank=True, max_length=100, null=True)),
                ('pejabat_acc', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.ContractType')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee')),
            ],
        ),
    ]
