# Generated by Django 2.2.5 on 2019-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20190925_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number_contract',
            field=models.CharField(max_length=100),
        ),
    ]
