# Generated by Django 2.2.5 on 2019-10-03 12:38

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_auto_20190926_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=django_fsm.FSMField(default='active', max_length=50),
        ),
    ]
