# Generated by Django 2.2.5 on 2019-09-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='employee.Employee'),
            preserve_default=False,
        ),
    ]
