# Generated by Django 2.2.5 on 2019-09-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190920_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupemployee',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee'),
        ),
    ]
