# Generated by Django 2.2.5 on 2019-09-25 07:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('employee', '0005_auto_20190925_0652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifyEmailGroup',
            new_name='EmailGroup',
        ),
        migrations.RemoveField(
            model_name='group',
            name='email_group',
        ),
    ]
