# Generated by Django 2.2.5 on 2019-09-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20190925_0702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailGroup',
            new_name='NotifyEmailGroup',
        ),
    ]
