# Generated by Django 2.2.5 on 2019-09-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20190925_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotifyEmailGroup',
            new_name='EmailGroup',
        ),
    ]
