# Generated by Django 2.2.5 on 2019-09-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20190925_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEmailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmailGroup')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Group')),
            ],
        ),
    ]
