# Generated by Django 2.2.5 on 2019-09-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_registeremailgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_of_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
